name: Generic Tuner Plugin Release

on:
  push:
    tags: 0.[0-9]+

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Version
        id: version
        run: echo "::set-output name=version::$(git describe --tags)"
      - name: Build Release
        run: make release
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.version }}
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Release ${{ steps.version.outputs.version }}"
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/gentuner-${{ steps.version.outputs.version }}.linux-amd64.zip
          asset_name: gentuner-${{ steps.version.outputs.version }}.linux-amd64.zip
          asset_content_type: application/x-gzip
