name: Generic Tuner Plugin Release

on:
  push:
    tags: 0.[0-9]+

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Release
        run: make release
        env:
          RELEASE_VERSION: ${{ github.ref }}
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Release ${{ github.ref }}"
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/gentuner-${{ github.ref }}.linux-amd64.zip
          asset_name: gentuner-${{ github.ref }}.linux-amd64.zip
          asset_content_type: application/x-gzip
